### ISSUE TITLE
Remove use of multiple deprecated methods

### ISSUE THREAD

**Issue by SahebChandok** [rajbhensdadiya/jmonkeyengineFall2024#4]
![Screenshot 2024-10-09 162356](https://github.com/user-attachments/assets/324e4d90-bace-421f-9244-7eec2a372a11)
![image](https://github.com/user-attachments/assets/8bce3343-8634-48c1-9e18-46d689f96f08)
![image](https://github.com/user-attachments/assets/c5334d3f-3581-4bb1-9f5f-9fc8930f9123)
![image](https://github.com/user-attachments/assets/19ab914f-ea04-4e64-8481-7fb8405a7b56)

A clear and concise description of what the technical debt is.
Depricated methods are still functional but are no longer recommended and may be removed in future versions of the framework or SDK. Continuing to use deprecated methods increases the risk that the app will break when upgrading to newer versions of Android. Developers who come across deprecated methods later may need to refactor large portions of the codebase, increasing the maintenance burden. This creates unnecessary work and slows down the development process.

**Screenshots**
![image](https://github.com/user-attachments/assets/e19b23d6-95dd-4f0f-b9dd-2e6a4211a4cf).
![image](https://github.com/user-attachments/assets/d300a047-e675-48ac-80c5-654d77f2ecc5)

Location:
File: AndroidHarness.java
Path: src/main/java/com/jme3/app/AndroidHarness.java

Reason for change:
The reason for the changes from methods like getHeight(), getWidth() and setBackgroundDrawable() to newer alternatives (getSize(), setBackground()) is to improve Android API consistency, maintainability, and performance over time.

**Comment by rajbhensdadiya** [comment]
Closing this issue in favour of this PR: #10
